#!/bin/sh

set -e -x

# for Ubuntu 16.04
#PACKAGES="git build-essential libssl-dev libncurses5-dev unzip gawk python subversion mercurial"
PACKAGES="git build-essential libssl-dev libncurses5-dev unzip gawk python subversion golang"
sudo apt -y install $PACKAGES

repo=https://git.lede-project.org/source.git
#repo=https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/openwrt
build_dir=lede-glibc
#build_dir=hwe-musl
if ! [ -d $build_dir ]; then
    git clone $repo $build_dir
fi
cd $build_dir

if ! grep -q '^config PERSISTENT_VAR' package/base-files/Makefile; then
    wget https://people.canonical.com/~teknoraver/openwrt_persistent_var.patch
    patch -p1 <openwrt_persistent_var.patch
fi

if ! grep '^src-git snap ' feeds.conf.default; then
    cat >>feeds.conf.default <<EOF
#src-git snap https://github.com/teknoraver/snap-openwrt
src-git snap https://github.com/lool/snap-openwrt
EOF
fi

./scripts/feeds update -a
./scripts/feeds install -a

if ! [ -r .config ]; then
    configs="../lede-configs/common"
    # glibc build (comment out for the default musl build)
    configs="$configs ../lede-configs/glibc"
    # luci web interface
    configs="$configs ../lede-configs/luci"
    # tcpdump
    configs="$configs ../lede-configs/tcpdump"
    # Raspberry Pi 3 B
    configs="$configs ../lede-configs/rpi3"
    cat $configs >.config
    make defconfig
fi

make -j`grep -c '^processor\>' /proc/cpuinfo`

